# Generated by Django 3.2 on 2021-04-13 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feriado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feriadomodel',
            name='modificado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='modificado em'),
        ),
    ]
